const KEYCLOAK_BASE_URL = process.env.KEYCLOAK_BASE_URL;
const KEYCLOAK_REALM = process.env.KEYCLOAK_REALM || 'master';
const KEYCLOAK_CLIENT_ID = process.env.KEYCLOAK_CLIENT_ID || 'exercise-app';
const KEYCLOAK_CLIENT_SECRET = process.env.KEYCLOAK_CLIENT_SECRET || '';


const KEYCLOAK_RESOURCE_REALM = process.env.KEYCLOAK_RESOURCE_REALM;
const KEYCLOAK_RESOURCE_BASE_URL = process.env.KEYCLOAK_RESOURCE_BASE_URL;
const KEYCLOAK_RESOURCE_CLIENT_ID = process.env.KEYCLOAK_RESOURCE_CLIENT_ID;
const KEYCLOAK_RESOURCE_CLIENT_SECRET = process.env.KEYCLOAK_RESOURCE_CLIENT_SECRET || '';

const REDIRECT_URI = process.env.KEYCLOAK_REDIRECT_URI;
const AGENDA_REDIRECT_URI = process.env.KEYCLOAK_RESOURCE_REDIRECT_URI;

const POST_LOGOUT_REDIRECT_URI = process.env.KEYCLOAK_POST_LOGOUT_REDIRECT_URI;
const RESOURCE_SERVER_URL = process.env.RESOURCE_SERVER_URL;


module.exports = {
  KEYCLOAK_BASE_URL,
  KEYCLOAK_REALM,
  KEYCLOAK_CLIENT_ID,
  KEYCLOAK_CLIENT_SECRET,
  KEYCLOAK_RESOURCE_REALM,
  KEYCLOAK_RESOURCE_CLIENT_ID,
  KEYCLOAK_RESOURCE_BASE_URL,
  KEYCLOAK_RESOURCE_CLIENT_SECRET,
  REDIRECT_URI,
  AGENDA_REDIRECT_URI,
  POST_LOGOUT_REDIRECT_URI,
  RESOURCE_SERVER_URL,
}
